### ISSUE TITLE
Exception ticking entity (Villagers)

### ISSUE THREAD

**Issue by BeanZephyron** [TeamMetallurgy/Atum2#250]
I absolutely love this mod! I did notice, however, that every time that the game attempts to spawn a villager in Atum 2, the game crashes. I have a list of several mods, and I am not sure if an incompatibility is causing the issue. I sincerely apologize for the crash log spam! Please let me know if you need me to pull anything else.

---- Minecraft Crash Report ----
// You're mean.

Time: 5/17/21 8:32 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mokiyoki.enhancedanimals.util.handlers.EventSubscriber.onLivingUpdateEvent(EventSubscriber.java:134) ~[?:0_6_29] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_437_EventSubscriber_onLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:339) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:little_critters.mixins.json:MixinMobEntity,pl:mixin:A}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.teammetallurgy.atum.entity.villager.AtumVillagerEntity.func_70071_h_(AtumVillagerEntity.java:268) ~[?:1.16.5-2.2.3] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mokiyoki.enhancedanimals.util.handlers.EventSubscriber.onLivingUpdateEvent(EventSubscriber.java:134) ~[?:0_6_29] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_437_EventSubscriber_onLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:339) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:little_critters.mixins.json:MixinMobEntity,pl:mixin:A}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.teammetallurgy.atum.entity.villager.AtumVillagerEntity.func_70071_h_(AtumVillagerEntity.java:268) ~[?:1.16.5-2.2.3] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:252) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: atum:villager_female (com.teammetallurgy.atum.entity.villager.AtumVillagerEntity)
	Entity ID: 2412
	Entity Name: Human Female
	Entity's Exact location: -309.50, 71.00, 16.50
	Entity's Block location: World: (-310,71,16), Chunk: (at 10,4,0 in -20,1; contains blocks -320,0,16 to -305,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:210) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Bean_Zephyron'/249, l='ClientLevel', x=-303.50, y=72.12, z=0.50]]
	Chunk stats: Client Chunk Cache: 225, 59
	Level dimension: atum:atum
	Level spawn location: World: (-240,64,-64), Chunk: (at 0,4,0 in -15,-4; contains blocks -240,0,-64 to -225,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2295 game time, 2295 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3013267656 bytes (2873 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.4
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		Kiwi-1.16.3-3.4.1.jar                             |Kiwi                          |kiwi                          |3.4.1               |DONE      |NOSIGNATURE
		mowziesmobs-1.5.15.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.15              |DONE      |NOSIGNATURE
		SereneShrubbery-1.16.5-1.1.0.jar                  |Serene Shrubbery              |serene_shrubbery              |1.0.0               |DONE      |NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |DONE      |NOSIGNATURE
		Wyrmroost-1.16.3-1.2.10.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.10       |DONE      |NOSIGNATURE
		Shrines-1.16.5-1.8.0-Beta1.jar                    |Shrines                       |shrines                       |1.16.5-1.8.0-Beta1  |DONE      |NOSIGNATURE
		ComfortableNether+2.5.jar                         |Comfortable Nether            |comfortable_nether            |1.0.0               |DONE      |NOSIGNATURE
		mcw-windows-1.0.3-mc1.16.5.jar                    |Macaw's Windows               |mcwwindows                    |1.0.3               |DONE      |NOSIGNATURE
		Fallingleaves-1.16.5-1.0.1.jar                    |Falling Leaves                |fallingleaves                 |1.0.1               |DONE      |NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |DONE      |NOSIGNATURE
		citadel-1.6.1.jar                                 |Citadel                       |citadel                       |1.6.1               |DONE      |NOSIGNATURE
		alexsmobs-1.10.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.10.1              |DONE      |NOSIGNATURE
		ColtCosmeticArmorMod-1.2.jar                      |Colt's Cosmetic Armour Mod    |ccam                          |1.0.1               |DONE      |NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |DONE      |NOSIGNATURE
		mcw-doors-1.0.1fix-mc1.16.4.jar                   |Macaw's Doors                 |mcwdoors                      |1.0.1               |DONE      |NOSIGNATURE
		foragecraft-1.16.5-2.2.1.jar                      |ForageCraft                   |foragecraft                   |2.2.1               |DONE      |5e:5d:44:da:52:81:e6:cb:5d:8e:12:80:3b:03:3f:d4:eb:96:92:ef:1a:03:d6:2b:06:f4:e0:57:c6:9b:27:b7
		iceandfire-2.1.6-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.6-1.16.4        |DONE      |NOSIGNATURE
		ironagefurniture+1.16.4-1.16.5+0.2.0.5.jar        |Iron Age Furniture            |ironagefurniture              |1.16.4-0.2.0        |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-universal.jar                 |Forge                         |forge                         |36.1.4              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		supplementaries-1.16.5-0.12.2.jar                 |Supplementaries               |supplementaries               |1.16.5-0.12.2       |DONE      |NOSIGNATURE
		betterendforge-1.16.4-1.6.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.4.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.4      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		forge-1.16.5-36.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.4.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |DONE      |NOSIGNATURE
		Modernxl+[1.16.5]+Fireplaces+update.jar           |Modernxl                      |minecraftmodernxl             |1.0.0               |DONE      |NOSIGNATURE
		Spheric+1.0.1+1.16.5.jar                          |Spheric                       |spheric                       |1.0.1               |DONE      |NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |NOSIGNATURE
		mcw-fences-1.0.0-mc1.16.5.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.0               |DONE      |NOSIGNATURE
		NDM+1.16.5+II+V0.21.3.4.jar                       |Natural Decor Mod             |naturaldecormod               |0.21.3.4            |DONE      |NOSIGNATURE
		GeneticAnimals-0_6_29.jar                         |Genetic Animals               |eanimod                       |0_6_29              |DONE      |NOSIGNATURE
		Endless-Ocean-Mod-1.16.5.jar                      |Endless Oceans                |endlessoceans                 |1.0.0               |DONE      |NOSIGNATURE
		DarkerDepths-1.16.5-1.0.1.jar                     |Darker Depths                 |darkerdepths                  |1.0.1}              |DONE      |NOSIGNATURE
		little_critters-0.0.1.jar                         |Little Critters Mod           |little_critters               |0.0.1               |DONE      |NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.2.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |NOSIGNATURE
		CNB-1.16.3_5-1.2.11.jar                           |Creatures and Beasts          |cnb                           |1.2.11              |DONE      |NOSIGNATURE
		whisperwoods-1.16.4-2.0.0.jar                     |Whisperwoods                  |whisperwoods                  |2.0.0               |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.0.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.0      |DONE      |NOSIGNATURE
		Atum-1.16.5-2.2.3.jar                             |Atum 2                        |atum                          |1.16.5-2.2.3        |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.0.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		betteranimals-1.16.4-5.5.0.jar                    |Cyber's Better Animal Models  |betteranimals                 |5.5.0               |DONE      |NOSIGNATURE
		ToughAsNails-1.16.5-4.0.1.23-universal.jar        |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.15     |DONE      |NOSIGNATURE
		BuddiesForBaby-1.16.4-v1.5.2.jar                  |Buddies For Baby              |buddies_for_baby              |1.5.2               |DONE      |NOSIGNATURE
		buildersaddition-1.16.5-20210517a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210517a    |DONE      |NOSIGNATURE
		fins-1.4.1.jar                                    |Fins and Tails                |fins                          |1.4.1               |DONE      |NOSIGNATURE
		mcws-roofs-2.0.0-mc1.16.4.jar                     |Macaw's Roofs                 |mcwroofs                      |2.0.0               |DONE      |NOSIGNATURE
		MrCrayfishs-Furniture-Mod-1.16.5.jar              |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
		LadyLucs+Critter_Mod_1.3.jar                      |LadyLucs' Critters            |ladys_critter_mod             |1.0.0               |DONE      |NOSIGNATURE
		mcw-furniture-2.0.0-mc1.16.4.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.0               |DONE      |NOSIGNATURE
		OddWaterMobs[1.16.5]_1.3.0.jar                    |Odd Water Mobs                |oddwatermobs                  |1.3.0               |DONE      |NOSIGNATURE
		NefsMedievalPubLite+v0.8.5(1.16.5).jar            |Nef Deco Mod Lite             |nefdecomod                    |0.8                 |DONE      |NOSIGNATURE
		byg-1.2.7.jar                                     |Oh The Biomes You'll Go       |byg                           |1.2.7               |DONE      |NOSIGNATURE
		bgcore-1.16.5-3.2.jar                             |bgcore                        |bgcore                        |3.2                 |DONE      |NOSIGNATURE
		Aquaculture-1.16.5-2.1.18.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.18       |DONE      |NOSIGNATURE
		smallships-1.16.5-1.8.4.jar                       |Small Ships Mod               |smallships                    |1.8.4               |DONE      |NOSIGNATURE
		exoticbirds-1.16.4-1.0.1.jar                      |Exotic Birds                  |exoticbirds                   |1.0.1               |DONE      |NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta10.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta10|DONE      |NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta8.jar           |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta8  |DONE      |NOSIGNATURE
		DragonSurvival-0.0.32-1.16.5.jar                  |Dragon Survival               |dragonsurvival                |0.0.32-1.16.5       |DONE      |NOSIGNATURE
		forge-1.16.5-geckolib-3.0.7.jar                   |GeckoLib                      |geckolib3                     |3.0.7               |DONE      |NOSIGNATURE
	Crash Report UUID: 4c91fcaf-2a4d-48fb-b19f-767589f5d575
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
	Patchouli open book context: n/a
	Launched Version: 1.16.5-forge-36.1.4
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-16.1.7, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/Dragon+Mounts+to+Wings+of+Fire, file/BVP+-+Better+Vanilla+Plants
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-16.1.7
	OpenGlRenderer: Intel(R) HD Graphics 6000
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by GirafiStudios** [comment]
Crash is caused by Genetic Animals, can't do anything about it on our end.
I would suggest reporting it to them.
