### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MxDeath** [TeamMetallurgy/Atum2#274]
I don't know what is going on, I'm trying to get into the dimension but every time I try it crashed the game. 

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 5/31/21 3:04 PM
Description: Checking entity block collision

java.lang.NegativeArraySizeException: null
	at net.minecraft.crash.CrashReportCategory.func_85070_b(CrashReportCategory.java:132) ~[?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:209) [?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:184) [?:?] {re:classloading}
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:598) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_233633_a_(LivingEntity.java:2053) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2014) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1368) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2449) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:489) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5736/897475380.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.crash.CrashReportCategory.func_85070_b(CrashReportCategory.java:132) ~[?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:209) ~[?:?] {re:classloading}
	at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:184) ~[?:?] {re:classloading}
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
-- Entity being checked for collision --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 174
	Entity Name: MxDeath
	Entity's Exact location: 117.10, 65.92, 42.49
	Entity's Block location: World: (117,65,42), Chunk: (at 5,4,10 in 7,2; contains blocks 112,0,32 to 127,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:598) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_233633_a_(LivingEntity.java:2053) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2014) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1368) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2449) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:489) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 174
	Entity Name: MxDeath
	Entity's Exact location: 117.10, 65.92, 42.49
	Entity's Block location: World: (117,65,42), Chunk: (at 5,4,10 in 7,2; contains blocks 112,0,32 to 127,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5736/897475380.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 810852512 bytes (773 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.24.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.24
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.24-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.24-universal.jar                |Forge                         |forge                         |36.1.24             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |Manifest: NOSIGNATURE
		Atum-1.16.5-2.2.4.jar                             |Atum 2                        |atum                          |1.16.5-2.2.4        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 64cfac48-6bd5-4172-acc3-12447f7ee653
	Player Count: 1 / 8; [ServerPlayerEntity['MxDeath'/174, l='ServerLevel[Testting]', x=117.10, y=65.92, z=42.49]]
	Data Packs: vanilla, mod:forge, mod:curios, mod:atum
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by GirafiStudios** [comment]
You're using the vanilla launcher, and something got corrupted. Either completely re-install Minecraft, or use another launcher, such as the CurseForge launcher.

**Comment by Ometia** [comment]
Hey, I'm getting this issue on my custom 1.16.5 pack, and I doubt your answer is correct. See, I'm getting two types of crashes, one generating terrain, one an entity collision. You said that something is likely corrupted on Minecraft itself, but I sorta doubt that. See, I didn't just test on my computer, but my friend's server as well (I'm developing the pack, but he's running a server on his computer). The crash happens on the server as well as one my single player world. If it is a corruption, we need to figure out where the corruption is happening, because it appears to be somewhat common. Also I'm using the curseforge launcher
[crash-2022-07-14_23.41.17-server.txt](https://github.com/TeamMetallurgy/Atum2/files/9126170/crash-2022-07-14_23.41.17-server.txt)
[crash-2022-07-15_15.44.08-server.txt](https://github.com/TeamMetallurgy/Atum2/files/9126171/crash-2022-07-15_15.44.08-server.txt)
[crash-2022-07-15_18.48.42-server.txt](https://github.com/TeamMetallurgy/Atum2/files/9126172/crash-2022-07-15_18.48.42-server.txt)
.

**Comment by Ometia** [comment]
I'll reinstall minecraft to see if that helps, but I sorta doubt it. Then again, I've been wrong before.
