### ISSUE TITLE
Crashing as soon as I enter the portal

### ISSUE THREAD

**Issue by m4tzzz** [TeamMetallurgy/Atum2#287]
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/12/21 10:44 AM
Description: Ticking player

java.lang.NegativeArraySizeException: null
	at net.minecraft.crash.CrashReportCategory.func_85070_b(CrashReportCategory.java:132) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:209) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:184) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_145775_I(LivingEntity.java:4055) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.checkBlockCollisions(LivingEntity.java:4017) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_213315_a(LivingEntity.java:3675) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_233633_a_(LivingEntity.java:2053) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2014) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1368) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:PlayerEntityMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.entity.LivingEntity.redirect$zco000$OnTravelRequest(LivingEntity.java:3485) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2449) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:489) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:PlayerEntityMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:PlayerEntityMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:advancement.ServerPlayerEntityMixin,pl:mixin:APP:performant.mixins.json:entity.ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.crash.CrashReportCategory.func_85070_b(CrashReportCategory.java:132) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:209) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.crash.CrashReport.func_85058_a(CrashReport.java:184) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_145775_I(LivingEntity.java:4055) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.checkBlockCollisions(LivingEntity.java:4017) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_213315_a(LivingEntity.java:3675) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_233633_a_(LivingEntity.java:2053) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2014) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1368) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:PlayerEntityMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.entity.LivingEntity.redirect$zco000$OnTravelRequest(LivingEntity.java:3485) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2449) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:489) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:PlayerEntityMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:accessor.ILivingEntityAccessor,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:LivingEntityMixin,pl:mixin:APP:performant.mixins.json:entity.LivingEntityUpdateEventMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:mixin:APP:META-INF/goldenagecombat.mixins.json:PlayerEntityMixin,pl:mixin:A,re:computing_frames,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 114
	Entity Name: _m4tz_
	Entity's Exact location: -12.17, 73.80, 63.60
	Entity's Block location: World: (-13,73,63), Chunk: (at 3,4,15 in -1,3; contains blocks -16,0,48 to -1,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.59, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:advancement.ServerPlayerEntityMixin,pl:mixin:APP:performant.mixins.json:entity.ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:unearthed.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11397102088 bytes (10869 MB) / 15065939968 bytes (14368 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.30.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.30.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.30
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.30-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		repurposed_structures-1.16.5-2.7.5-forge.jar      |Repurposed Structures         |repurposed_structures         |1.16.5-2.7.5-forge  |DONE      |Manifest: NOSIGNATURE
		tod-1.16.5-1.2.0.jar                              |Tons o' Dungeons              |dungeons                      |1.2.0               |DONE      |Manifest: NOSIGNATURE
		GoldenAgeCombat-v1.5.2-1.16.5.jar                 |Golden Age Combat             |goldenagecombat               |1.5.2               |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.16.5-2.4.jar                      |Tree Harvester                |treeharvester                 |2.4                 |DONE      |Manifest: NOSIGNATURE
		unearthed-1.1.2c.jar                              |Unearthed                     |unearthed                     |1.1.2c              |DONE      |Manifest: NOSIGNATURE
		EnchantingConvergence-1.16.5-1.0.0.jar            |Enchanting Convergence        |enchanting_convergence        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughItems-6.0.0.232-alpha-forge.jar      |Roughly Enough Items          |roughlyenoughitems            |6.0.0.232-alpha     |DONE      |Manifest: NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.16.4-1.6.1.jar                  |Majrusz Library               |majrusz_library               |1.6.1               |DONE      |Manifest: NOSIGNATURE
		dimdungeons-1.12-forge-1.16.5.jar                 |Dimensional Dungeons          |dimdungeons                   |1.16.4-1.12         |DONE      |Manifest: NOSIGNATURE
		wonderful-enchantments-1.16.4-1.3.3.jar           |Wonderful Enchantments        |wonderful_enchantments        |1.3.3               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.9.0.1_Forge_1.16.5.jar          |Xaero's Minimap               |xaerominimap                  |21.9.0.1            |DONE      |Manifest: NOSIGNATURE
		omnis_backpacks-1.1.0.jar                         |Omnis Backpacks               |omnis_backpacks               |1.1.0               |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                |DONE      |Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |Manifest: NOSIGNATURE
		CookingForBlockheads_1.16.5-9.3.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.3.2               |DONE      |Manifest: NOSIGNATURE
		performant-1.16.2-5-3.40m.jar                     |Performant                    |performant                    |3.40m               |DONE      |Manifest: NOSIGNATURE
		configured-0.4.0-1.16.3.jar                       |Configured                    |configured                    |0.4.0-1.16.3        |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.16.5-20210517a.jar             |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210517a    |DONE      |Manifest: NOSIGNATURE
		architectury-1.17.18-forge.jar                    |Architectury                  |architectury                  |1.17.18             |DONE      |Manifest: NOSIGNATURE
		catalogue-1.0.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |DONE      |Manifest: NOSIGNATURE
		FpsReducer-mc1.16.4-1.18.jar                      |FPS Reducer                   |fpsreducer                    |mc1.16.4-1.18       |DONE      |Manifest: NOSIGNATURE
		battletowerslite.jar                              |Battle Towers Reforged        |battle_towers_reforged        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.30-universal.jar                |Forge                         |forge                         |36.1.30             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Atum-1.16.5-2.2.4.jar                             |Atum 2                        |atum                          |1.16.5-2.2.4        |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.490-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 93aacd42-793b-4562-a98c-c71b9b52bb10
	Player Count: 1 / 8; [ServerPlayerEntity['_m4tz_'/114, l='ServerLevel[lipsync for ur life!]', x=-12.17, y=73.80, z=63.60]]
	Data Packs: vanilla, mod:goldenagecombat, mod:treeharvester, mod:unearthed, mod:enchanting_convergence, mod:roughlyenoughitems, mod:torohealth, mod:majrusz_library, mod:dimdungeons, mod:wonderful_enchantments, mod:curios, mod:xaerominimap, mod:omnis_backpacks, mod:collective, mod:ctm (incompatible), mod:cookingforblockheads (incompatible), mod:configured, mod:buildersaddition (incompatible), mod:architectury, mod:catalogue, mod:cloth-config (incompatible), mod:fpsreducer, mod:forge, mod:atum, mod:twilightforest, mod:repurposed_structures, mod:dungeons, mod:performant (incompatible), mod:battle_towers_reforged
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by GirafiStudios** [comment]
Your vanilla launcher is broken. Reinstall it, or use some other launcher.
Also, please do not just paste crash logs directly into Github, your issue will be closed. Use gist.github.com, to create a link to it instead.
