### ISSUE TITLE
Occasional CTD in Atum2

### ISSUE THREAD

**Issue by jaynesb** [TeamMetallurgy/Atum2#325]
Minecraft: 1.16.5
Forge: 36.2.2
Atum2: 2.2.6

With the versions above, I've had a few crash to desktops while wandering around in Atum, with errors that look like the following:
```
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, east, south, west, up, down]} as it does not exist in Block{atum:sand}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.teammetallurgy.atum.blocks.trap.tileentity.TrapTileEntity.func_73660_a(TrapTileEntity.java:97) ~[atum:1.16.5-2.2.6] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:APP:brazier-common.mixins.json:WorldMixin,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:175) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaeroworldmap:xaero_wm_clientworld_getblockcolor,xf:fml:xaerominimapfair:xaero_clientworld_getblockcolor,xf:fml:xaerominimapfair:xaero_clientworld_getblockcolorraw,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimapfair:xaero_clientworldclass,pl:mixin:APP:betterweather.mixins.json:client.MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
```

Full crash reports attached.
[crash-2021-08-03_18.32.00-client.txt](https://github.com/TeamMetallurgy/Atum2/files/6927986/crash-2021-08-03_18.32.00-client.txt)
[crash-2021-08-03_18.19.36-client.txt](https://github.com/TeamMetallurgy/Atum2/files/6927987/crash-2021-08-03_18.19.36-client.txt)

**Comment by sscards55** [comment]
Could you disable the chunk access optimization inf the Flywheel mod and see if you still crash?

**Comment by jaynesb** [comment]
I'm not sure how to do that. It doesn't appear to be a config option or command for Flywheel anywhere.

I did go ahead and do some extra testing. I can't reproduce the issue with a tiny pack with _just_ Atum2. I then added Flywheel into that pack, made a new world, and tried again, and I'm still unable to repro. So if it's Flywheel, it's not just Flywheel on its own?

I can try to work my way back up to the full list from my original crash if you think that'll help, but it may take a while.

**Comment by sscards55** [comment]
I'm only assuming that's the cause because of the crash. The code is trying to cast "void air" as traps, and one of the only ways to do that is if something is messing with the loaded chunk positions or someone messed with the code that returns block based on position. Flywheel has that which is why I mentioned it.

**Comment by GirafiStudios** [comment]
While this is most likely caused by another mod, I can make a simple workaround.
Will be avaialbe in the next release. Can grab a Jenkins build here in the meantime: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.16.5%20Jenkins/275/

**Comment by sscards55** [comment]
Sadly this worn't fix it. since it's also getting cast as sand and limestone.

**Comment by GirafiStudios** [comment]
> Sadly this worn't fix it. since it's also getting cast as sand and limestone.

It is, yes. But you´re reading the crash wrong, if you´re saying that.
