### ISSUE TITLE
Crash error near particular area

### ISSUE THREAD

**Issue by mactso** [TeamMetallurgy/Atum2#346]
When any player goes near a location in Atum2: the game crashes.
-2329.14, y=74.86, z=3608.36]
Seed: [-2263577824371911604]

Appears to be trying to cancel a spawn event that can't be cancelled.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 9/16/21 10:38 AM
Description: Exception ticking world

java.lang.UnsupportedOperationException: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.event.entity.living.LivingSpawnEvent.CheckSpawn
	at net.minecraftforge.eventbus.api.Event.setCanceled(Event.java:95) ~[eventbus-4.0.0.jar:?] {}
	at com.teammetallurgy.atum.misc.event.AtumEventListener.checkSpawn(AtumEventListener.java:237) ~[atum:1.16.5-2.2.7] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_633_AtumEventListener_checkSpawn_CheckSpawn.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:201) ~[forge:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.ForgeHooks.canEntitySpawn(ForgeHooks.java:1179) ~[forge:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:172) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.eventbus.api.Event.setCanceled(Event.java:95) ~[eventbus-4.0.0.jar:?] {}
	at com.teammetallurgy.atum.misc.event.AtumEventListener.checkSpawn(AtumEventListener.java:237) ~[atum:1.16.5-2.2.7] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_633_AtumEventListener_checkSpawn_CheckSpawn.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:201) ~[forge:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.common.ForgeHooks.canEntitySpawn(ForgeHooks.java:1179) ~[forge:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:172) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:351) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['MacTso'/249, l='ServerLevel[forge-1-16-5-36.2.0]', x=-2329.14, y=74.86, z=3608.36]]
	Chunk stats: ServerChunkCache: 2210
	Level dimension: atum:atum
	Derived: true
	Level spawn location: World: (42,88,84), Chunk: (at 10,5,4 in 2,5; contains blocks 32,0,80 to 47,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 58438641 game time, 54729 day time
	Level name: forge-1-16-5-36.2.0
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 13310 (now: false), thunder time: 53050 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 3.10.0-1062.12.1.el7.x86_64
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141811688 bytes (135 MB) / 913833984 bytes (871 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 6
	JVM Flags: 6 total; -Xms256M -Xmx6144M -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		TrashSlot_1.16.3-12.2.1.jar                       |TrashSlot                     |trashslot                     |12.2.1              |DONE      |Manifest: NOSIGNATURE
		bagofyurting-1.16.4-1.2.0.1.jar                   |Bag of Yurting                |bagofyurting                  |1.2.0.1             |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.121.jar                          |Just Enough Items             |jei                           |7.7.1.121           |DONE      |Manifest: NOSIGNATURE
		dungeons_mobs-1.16.5-1.0.10.jar                   |Dungeons Mobs                 |dungeons_mobs                 |1.0.10              |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.3.jar                        |Waystones                     |waystones                     |7.6.3               |DONE      |Manifest: NOSIGNATURE
		HarderBranchMining-1.36.0.8.jar                   |Harder Branch Mining Mod      |harderbranchmining            |1.36.0.8            |DONE      |Manifest: NOSIGNATURE
		NastyMobs-1.16.3-1.0.0.8.jar                      |Nasty Mobs                    |nasty                         |1.0.0.8             |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.1.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.1      |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.0              |DONE      |Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.16.5-1.4.1.jar             |Simple Storage Network        |storagenetwork                |1.16.5-1.4.1        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		SereneSeasons-1.16.5-4.0.1.121-universal.jar      |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.121    |DONE      |Manifest: NOSIGNATURE
		OuterEnd-0.2.14.jar                               |The Outer End                 |outer_end                     |0.2.9               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.16.5-2.3.2.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.2               |DONE      |Manifest: NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |Manifest: d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		HarderSpawners-1.16.5-1.36.0.16.jar               |Harder Spawners Mod           |harderspawners                |1.36.0.16           |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		HostileWaterMonsters-1.36.1.18.jar                |Hostile Water Mobs            |hostilewatermobs              |1.36.1.18           |DONE      |Manifest: NOSIGNATURE
		traverse-1.16.4-0.4.3.8.jar                       |Traverse: Reforged            |traverse                      |1.16.4-0.4.3.8      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		SpawnBalanceUtility-1.36.0.11.jar                 |SpawnBalanceUtility           |spawnbalanceutility           |1.36.0.11           |DONE      |Manifest: NOSIGNATURE
		corpse-1.16.5-1.0.5.jar                           |Corpse                        |corpse                        |1.16.5-1.0.5        |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.47-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.47              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-server.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.2.4+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.2.4+1.16.5        |DONE      |Manifest: NOSIGNATURE
		livingthings-1.16.5-1.3.1.jar                     |Living Things                 |livingthings                  |1.16.5 - 1.3.1      |DONE      |Manifest: NOSIGNATURE
		EasierSleeping-1.16.5-2.0.0.jar                   |Easier Sleeping               |easier_sleeping               |2.0.0               |DONE      |Manifest: NOSIGNATURE
		Beekeeper-1.16.2-1.0.0.4.jar                      |Beekeeper                     |bk                            |1.0.0.4             |DONE      |Manifest: NOSIGNATURE
		SaveYourPets-1.16.2-1.0.0.5.jar                   |Save Your Pets                |syp                           |1.0.0.5             |DONE      |Manifest: NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |DONE      |Manifest: NOSIGNATURE
		dimdungeons-1.13.1.jar                            |Dimensional Dungeons          |dimdungeons                   |1.16.4-1.13.1       |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		Atum-1.16.5-2.2.7.jar                             |Atum 2                        |atum                          |1.16.5-2.2.7        |DONE      |Manifest: NOSIGNATURE
		collective-1.16.5-2.64.jar                        |Collective                    |collective                    |2.64                |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.3.0.jar                   |Storage Drawers               |storagedrawers                |8.3.0               |DONE      |Manifest: NOSIGNATURE
		Regrowth-1.16.4-1.16.5-1.35.0.22.jar              |Regrowth Mod                  |regrowth                      |1.16.5-1.35.0.22    |DONE      |Manifest: NOSIGNATURE
		RedstoneMagic-1.16.4-1.16.5-1.4.0.36.jar          |Redstone Magic                |redstonemagic                 |1.16.5-1.4.0.36     |DONE      |Manifest: NOSIGNATURE
		HappyTrails-1.16.5-1.36.0.8.jar                   |Happy Trails Mod              |happytrails                   |1.16.5-1.36.0.8     |DONE      |Manifest: NOSIGNATURE
		TheAbyss2 1.9.7 1.16.5.jar                        |TheAbyss                      |theabyss                      |1.9.7               |DONE      |Manifest: NOSIGNATURE
		sleepsooner_1.16.5-2.5.jar                        |Sleep Sooner                  |sleepsooner                   |2.5                 |DONE      |Manifest: NOSIGNATURE
		HarderNaturalHealing-1.36.0.6.jar                 |Harder Natural Healing Mod    |hardernaturalhealing          |1.36.0.6            |DONE      |Manifest: NOSIGNATURE
		Quick Harvest-1.16.5-1.4.0.jar                    |Quick Harvest                 |quickharvest                  |1.4.0               |DONE      |Manifest: NOSIGNATURE
		orcinusscaves-1.3.jar                             |Orcinus's Cavern              |cavern                        |{1.2.0}             |DONE      |Manifest: NOSIGNATURE
		TA2 beginning 1.0.9 1.16.5.jar                    |[Add-on] The Abyss: The Beginn|thebeginning                  |1.0.9               |DONE      |Manifest: NOSIGNATURE
		HarderFarther-1.16.5-1.36.0.6.jar                 |Harder Farther Mod            |harderfarther                 |1.36.0.6            |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.3.434-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.3.434           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.16.5-2.8.0.168-universal.jar       |EnderStorage                  |enderstorage                  |2.8.0.168           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		SpeakerMod-1.36.0.5.jar                           |SpeakerMod                    |speakermod                    |1.36.0.5            |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 49ecb25c-91af-44bf-bf37-55e7eb182d5d
	Player Count: 1 / 60; [ServerPlayerEntity['MacTso'/249, l='ServerLevel[forge-1-16-5-36.2.0]', x=-2329.14, y=74.86, z=3608.36]]
	Data Packs: vanilla, mod:harderbranchmining, mod:nasty, mod:mutantbeasts (incompatible), mod:harderspawners (incompatible), mod:hostilewatermobs (incompatible), mod:forge, mod:spawnbalanceutility (incompatible), mod:dungeons_arise, mod:easier_sleeping, mod:bk, mod:sf, mod:dimdungeons, mod:curios, mod:atum, mod:collective, mod:regrowth, mod:redstonemagic (incompatible), mod:hardernaturalhealing (incompatible), mod:harderfarther, mod:speakermod (incompatible), mod:dungeoncrawl, mod:sleepsooner, mod:citadel (incompatible), mod:alexsmobs, mod:cavern, mod:bagofyurting (incompatible), mod:abnormals_core, mod:outer_end, mod:codechickenlib (incompatible), mod:enderstorage (incompatible), mod:storagedrawers (incompatible), mod:repurposed_structures, mod:jei, mod:corpse, mod:livingthings, mod:trashslot (incompatible), mod:dungeons_mobs (incompatible), mod:sereneseasons, mod:happytrails, mod:waila, mod:traverse (incompatible), mod:waystones (incompatible), mod:storagenetwork, mod:quickharvest, mod:syp, mod:comforts, mod:invtweaks (incompatible), mod:theabyss, mod:thebeginning
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by mactso** [comment]
May just need a try/catch here :
Or may need to test if the event is cancellable before trying to cancel it.

java.lang.UnsupportedOperationException: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.event.entity.living.LivingSpawnEvent.CheckSpawn
at net.minecraftforge.eventbus.api.Event.setCanceled(Event.java:95) ~[eventbus-4.0.0.jar:?] {}
**at com.teammetallurgy.atum.misc.event.AtumEventListener.checkSpawn(AtumEventListener.java:237) ~[atum:1.16.5-2.2.7] {re:classloading}**

**Comment by mactso** [comment]
It looks like you fixed this issue with the new patch so I'm closing this!

I guess it was assassins in spawners in the large stand alone buildings.
