### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Jackc2021** [TeamMetallurgy/Atum2#378]
WARNING: coremods are present:
  Snow! Real Magic! (SnowRealMagic-1.12.2-0.5.6.jar)
  ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
  OTGCorePlugin (OTG-Core.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  MixinBooter (.mixinbooter-4.0.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  LoliASM (loliasm-4.4.1.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.8.0-core.jar)
  Pick Up Notifier (PickUpNotifier-v1.1.5-1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  KonkreteCore (konkrete_1.3.0_MC_1.12-1.12.2.jar)
  FMCore (fancymenu_2.3.6_MC_1.12-1.12.2.jar)
  Sneaky Curses (SneakyCurses-v1.0.1-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  MSICCoreMod (MyServerIsCompatible-1.12.2-1.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  midnight (themidnight-0.3.5.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  Aqua Acrobatics Transformer (AquaAcrobatics-v1.3.5-1.12.2.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.4.1.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.3.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/3/22 10:17 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Atum 2 (atum)
Caused by: java.lang.NullPointerException
	at com.teammetallurgy.atum.init.AtumRecipes.addKilnRecipes(AtumRecipes.java:175)
	at com.teammetallurgy.atum.Atum.init(Atum.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 881230992 bytes (840 MB) / 1758986240 bytes (1677 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 LoliASM 4.4.1 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G6_pre1 156 mods loaded, 156 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                           | Version             | Source                                           | Signature                                |
	|:----- |:---------------------------- |:------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHI  | minecraft                    | 1.12.2              | minecraft.jar                                    | None                                     |
	| LCHI  | mcp                          | 9.42                | minecraft.jar                                    | None                                     |
	| LCHI  | FML                          | 8.0.99.99           | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                        | 14.23.5.2855        | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | ivtoolkit                    | 1.3.3-1.12          | minecraft.jar                                    | None                                     |
	| LCHI  | otgcore                      | 1.12.2-v9.3         | minecraft.jar                                    | None                                     |
	| LCHI  | mixinbooter                  | 4.0                 | minecraft.jar                                    | None                                     |
	| LCHI  | foamfixcore                  | 7.7.4               | minecraft.jar                                    | None                                     |
	| LCHI  | dgcd                         | 1.0.0               | 1.3dgcd.jar                                      | None                                     |
	| LCHI  | dead_guys_pork_and_more_pork | 1.0.0               | 1.6dgpamp.jar                                    | None                                     |
	| LCHI  | movillages                   | 1.5.4               | [1.12]MoVillages-1.5.4.jar                       | None                                     |
	| LCHI  | aether_legacy                | 1.5.3.2             | aether-1.12.2-v1.5.3.2.jar                       | None                                     |
	| LCHI  | akashictome                  | 1.2-12              | AkashicTome-1.2-12.jar                           | None                                     |
	| LCHI  | ambients                     | 1.12.2-1.2.0        | ambients-1.2.0.jar                               | None                                     |
	| LCHI  | ancientbeasts                | 1.0                 | ancientbeasts-1.6.jar                            | None                                     |
	| LCHI  | antiqueatlas                 | 4.6.3               | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCHI  | antiqueatlasoverlay          | 1.2                 | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCHI  | crafttweaker                 | 4.1.20              | CraftTweaker2-1.12-4.1.20.670.jar                | None                                     |
	| LCHI  | jei                          | 4.16.1.301          | jei_1.12.2-4.16.1.301.jar                        | None                                     |
	| LCHI  | appleskin                    | 1.0.14              | AppleSkin-mc1.12-1.0.14.jar                      | None                                     |
	| LCHI  | aquaacrobatics               | 1.3.5               | AquaAcrobatics-v1.3.5-1.12.2.jar                 | None                                     |
	| LCHI  | aquaculture                  | 1.6.8               | Aquaculture-1.12.2-1.6.8.jar                     | None                                     |
	| LCHI  | atlasextras                  | 1.8                 | AtlasExtras-1.12.2-1.8.jar                       | None                                     |
	| LCHI  | attributefix                 | 1.0.4               | AttributeFix-1.12.2-1.0.4.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHE  | atum                         | 2.0.20              | Atum-1.12.2-2.0.20.jar                           | None                                     |
	| LCH   | quark                        | r1.6-179            | Quark-r1.6-179.jar                               | None                                     |
	| LCH   | autoreglib                   | 1.3-32              | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCH   | badmobs                      | 1.1.40              | BadMobs-1.12.2-1.1.40.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | betteradvancements           | 0.1.0.77            | BetterAdvancements-1.12.2-0.1.0.77.jar           | None                                     |
	| LCH   | bettercaves                  | 1.12.2              | bettercaves-1.12.2-2.0.4.jar                     | None                                     |
	| LCH   | bettercompass                | 1.5.0               | bettercompass-1.12.2-1.5.0.jar                   | None                                     |
	| LCH   | forgelin                     | 1.8.4               | Forgelin-1.8.4.jar                               | None                                     |
	| LCH   | betterfoliage                | 2.3.2               | BetterFoliage-MC1.12-2.3.3.jar                   | None                                     |
	| LCH   | bettermineshafts             | 1.12.2-2.2.1        | BetterMineshaftsForge-1.12.2-2.2.1.jar           | None                                     |
	| LCH   | wildlands_alpha              | 0.1                 | Wildlands-1.12.2-alpha-0.1.jar                   | None                                     |
	| LCH   | openterraingenerator         | v9.3                | OpenTerrainGenerator-1.12.2-v9.3.jar             | None                                     |
	| LCH   | biomebundle                  | 5.1                 | Biome_Bundle-1.12.2-v6.1.jar                     | None                                     |
	| LCH   | biomesoplenty                | 7.0.1.2441          | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar    | None                                     |
	| LCH   | bbop                         | 1.0                 | Biome_Bundle_O_Plenty-1.12.2_v1.0.jar            | None                                     |
	| LCH   | biomeinfo                    | v1.2.5              | biomeinfo-1.12.2-v1.2.5.jar                      | None                                     |
	| LCH   | blockdrops                   | 1.4.0               | blockdrops-1.12.2-1.4.0.jar                      | None                                     |
	| LCH   | bloodmoon                    | 1.5.3               | Bloodmoon-MC1.12.2-1.5.3.jar                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | blue_skies                   | 1.1.3               | blue_skies-1.12.2-v1.1.3.jar                     | None                                     |
	| LCH   | bookshelf                    | 2.3.590             | Bookshelf-1.12.2-2.3.590.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | bountiful                    | 2.2.2               | Bountiful-2.2.2.jar                              | None                                     |
	| LCH   | carryon                      | 1.12.3              | carryon-1.12.2-1.12.6.20.jar                     | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCH   | cavegenerator                | 1.1                 | CaveGenerator-1.1.jar                            | None                                     |
	| LCH   | charm                        | 1.4                 | Charm-1.12.2-1.4.1.jar                           | None                                     |
	| LCH   | cherishedworlds              | 1.12.2-1.0.1        | cherishedworlds-1.12.2-1.0.1.jar                 | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | clienttweaks                 | 3.1.11              | ClientTweaks_1.12.2-3.1.11.jar                   | None                                     |
	| LCH   | clumps                       | 3.1.2               | Clumps-3.1.2.jar                                 | None                                     |
	| LCH   | collective                   | 3.0                 | collective-1.12.2-3.0.jar                        | None                                     |
	| LCH   | combustfish                  | 1.0.3.4             | combustfish-1.12.2-1.0.3.4.jar                   | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | comforts                     | 1.4.1.3             | comforts-1.12.2-1.4.1.3.jar                      | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCH   | controlling                  | 3.0.10              | Controlling-3.0.10.jar                           | None                                     |
	| LCH   | extendedrenderer             | v1.0                | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LCH   | coroutil                     | 1.12.1-1.2.37       | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LCH   | configmod                    | v1.0                | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LCH   | corpse                       | 1.12.2-1.0.8        | corpse-1.12.2-1.0.8.jar                          | None                                     |
	| LCH   | ctgui                        | 1.0.0               | CraftTweaker2-1.12-4.1.20.670.jar                | None                                     |
	| LCH   | crafttweakerjei              | 2.0.3               | CraftTweaker2-1.12-4.1.20.670.jar                | None                                     |
	| LCH   | customstartinggear           | 1.2.0               | CustomStartingGear-1.12-1.2.0.9-universal.jar    | None                                     |
	| LCH   | ding                         | 1.0.2               | Ding-1.12.2-1.0.2.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | discordcraft                 | 1.0                 | DiscordCraft-2.0.jar                             | None                                     |
	| LCH   | divergentunderground         | 0.64.0              | Divergent-Underground-1.12-0.64.0.jar            | None                                     |
	| LCH   | dragonmounts                 | 1.12.2-1.6.3        | DragonMounts2-1.12.2-1.6.3.jar                   | None                                     |
	| LCH   | sereneseasons                | 1.2.18              | SereneSeasons-1.12.2-1.2.18-universal.jar        | None                                     |
	| LCH   | orelib                       | 3.6.0.1             | OreLib-1.12.2-3.6.0.1.jar                        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                    | 3.6.1.0             | DynamicSurroundings-1.12.2-3.6.1.0.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dynview                      | 1.3                 | dynviewdist-1.12-1.3.jar                         | None                                     |
	| LCH   | eerieentities                | 1.0.7               | EerieEntities-1.12.2-1.0.7.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | elevatorid                   | 1.3.14              | ElevatorMod-1.12.2-1.3.14.jar                    | None                                     |
	| LCH   | enchdesc                     | 1.1.15              | EnchantmentDescriptions-1.12.2-1.1.15.jar        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | endreborn                    | 0.3.8               | EndReborn [0.3.9].jar                            | None                                     |
	| LCH   | exoticbirds                  | 1.0                 | Exotic Birds 1.12.2-3.2.0.jar                    | None                                     |
	| LCH   | familiarfauna                | 1.0.11              | FamiliarFauna-1.12.2-1.0.11.jar                  | None                                     |
	| LCH   | konkrete                     | 1.3.0               | konkrete_1.3.0_MC_1.12-1.12.2.jar                | None                                     |
	| LCH   | fancymenu                    | 2.3.6               | fancymenu_2.3.6_MC_1.12-1.12.2.jar               | None                                     |
	| LCH   | foamfix                      | 0.10.14-1.12.2      | foamfix-0.10.14-1.12.2.jar                       | None                                     |
	| LCH   | iceologer                    | 1.5.1               | Frozen-Fiend-1.5.1.jar                           | None                                     |
	| LCH   | ftbbackups                   | 1.1.0.1             | FTBBackups-1.1.0.1.jar                           | None                                     |
	| LCH   | futureminecraf               | 1.3.1               | FutureVersions v1.3.1.jar                        | None                                     |
	| LCH   | guardillagers                | 1.0.1               | guardillagers-1.12.2-1.0.1.jar                   | None                                     |
	| LCH   | guicompass                   | 1.5                 | guicompass_1.12.2-1.5.jar                        | None                                     |
	| LCH   | hunterillager                | 1.2                 | hunterillager-1.12.2-1.2.jar                     | None                                     |
	| LCH   | waila                        | 1.8.26              | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCH   | improvedbackpacks            | 1.12.2-1.5.0.0      | ImprovedBackpacks-1.12.2-1.5.0.0.jar             | None                                     |
	| LCH   | incontrol                    | 3.9.18              | incontrol-1.12-3.9.18.jar                        | None                                     |
	| LCH   | inventoryhud                 | 3.4.0               | InventoryHUD-1.12.2.forge-3.4.1.jar              | None                                     |
	| LCH   | itlt                         | 1.0.4               | itlt-1.12.x-1.0.4.jar                            | None                                     |
	| LCH   | jeiintegration               | 1.6.0               | jeiintegration_1.12.2-1.6.0.jar                  | None                                     |
	| LCH   | jeivillagers                 | 1.0                 | jeivillagers-1.12-1.0.2.jar                      | None                                     |
	| LCH   | jepb                         | 1.2.1               | jepb-1.12-1.2.1.jar                              | None                                     |
	| LCH   | jeresources                  | 0.9.2.60            | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
	| LCH   | jeroreintegration            | 1.1.0               | JEROreIntegration-1.12.2-1.1.0.jar               | None                                     |
	| LCH   | jojobadv                     | 1.1.2               | JojoBAdv-1.1.2 - 12.2.2.jar                      | None                                     |
	| LCH   | brewcraft                    | 1.12.2-1.0.2        | Pam's BrewCraft 1.12.2-1.0.2.jar                 | None                                     |
	| LCH   | jebc                         | 1.0.2               | just-enough-brewcraft-1.12.2-1.0.2.jar           | None                                     |
	| LCH   | harvestcraft                 | 1.12.2zb            | Pam's HarvestCraft 1.12.2zg.jar                  | None                                     |
	| LCH   | jehc                         | 1.7.2               | just-enough-harvestcraft-1.12.2-1.7.2.jar        | None                                     |
	| LCH   | jecalculation                | 1.12.2-3.2.7        | JustEnoughCalculation-1.12.2-3.2.7.jar           | None                                     |
	| LCH   | libraryex                    | 1.2.2               | LibraryEx-1.12.2-1.2.2.jar                       | None                                     |
	| LCH   | sturcturemod                 | 0.1                 | Little_Structures_mod_1.12.2_v1.0.jar            | None                                     |
	| LCH   | loliasm                      | 4.4.1               | loliasm-4.4.1.jar                                | None                                     |
	| LCH   | lucky                        | 7.6.0               | luckyblock-1.12.2-1-forge.jar                    | None                                     |
	| LCH   | lycanitesmobs                | 2.0.8.4 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.8.4.jar                 | None                                     |
	| LCH   | modularexpansionend          | 1.1.0               | Modular Expansion - End 1.1 (MC 1.12.2).jar.jar  | None                                     |
	| LCH   | guilib                       | $version            | morepaintings-paintings-1.12.2-5.0.1.2.jar       | None                                     |
	| LCH   | paintingselgui               | $version            | morepaintings-paintings-1.12.2-5.0.1.2.jar       | None                                     |
	| LCH   | morepaintings                | $version            | morepaintings-paintings-1.12.2-5.0.1.2.jar       | None                                     |
	| LCH   | mousetweaks                  | 2.10                | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
	| LCH   | llibrary                     | 1.7.20              | llibrary-1.7.20-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | mowziesmobs                  | 1.5.8               | mowziesmobs-1.5.8.jar                            | None                                     |
	| LCH   | multimob                     | 1.0.5               | multimob-1.0.5.jar                               | None                                     |
	| LCH   | msic                         | 1.0                 | MyServerIsCompatible-1.12.2-1.0.jar              | None                                     |
	| LCH   | naturescompass               | 1.8.5               | NaturesCompass-1.12.2-1.8.5.jar                  | None                                     |
	| LCH   | netherex                     | 2.2.5               | NetherEx-1.12.2-2.2.5.jar                        | None                                     |
	| LCH   | nutrition                    | 4.9.0               | Nutrition-1.12.2-4.9.0.jar                       | None                                     |
	| LCH   | overpoweredarmorbar          | @VERSION@           | overloadedarmorbar-1.0.4g.jar                    | None                                     |
	| LCH   | particleculling              | v1.3                | particleculling-1.12.2-v1.3.1.jar                | None                                     |
	| LCH   | pickupnotifier               | 1.1.5               | PickUpNotifier-v1.1.5-1.12.2.jar                 | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCH   | pillageplunder               | 1.0.0               | PillagePlunder_1.12.2_[BETA]0.1.0.jar            | None                                     |
	| LCH   | primitivemobs                | 1.2.3a              | primitivemobs-1.2.3a.jar                         | None                                     |
	| LCH   | reccomplex                   | 1.4.8.2             | RecurrentComplex-1.4.8.2.jar                     | None                                     |
	| LCH   | additionalstructures         | 2.4.1               | Rex's-Additional-Structures-1.12.x-(v.2.4.1).jar | None                                     |
	| LCH   | roguelike                    | 1.8.0               | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| LCH   | storagenetwork               | 1.8.0               | SimpleStorageNetwork-1.12.2-1.8.0.jar            | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCH   | sit                          | v1.3                | sit-1.12.2-v1.3.jar                              | None                                     |
	| LCH   | sneakycurses                 | 1.0.1               | SneakyCurses-v1.0.1-1.12.2.jar                   | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCH   | snowrealmagic                | 0.5.6               | SnowRealMagic-1.12.2-0.5.6.jar                   | None                                     |
	| LCH   | soundfilters                 | 0.12.1_for_1.12     | SoundFilters-0.12.1_for_1.12.jar                 | None                                     |
	| LCH   | spartanweaponry              | 1.4.1               | SpartanWeaponry-1.12.2-1.4.1.jar                 | None                                     |
	| LCH   | spartancompat                | @VERSION@           | spartancompat-1.2.3.jar                          | None                                     |
	| LCH   | spartanshields               | 1.5.5               | SpartanShields-1.12.2-1.5.5.jar                  | None                                     |
	| LCH   | stg                          | 1.12.2-1.2.3        | stg-1.12.2-1.2.3.jar                             | None                                     |
	| LCH   | strawgolem                   | 1.3                 | strawgolem-1.4.1.jar                             | None                                     |
	| LCH   | theaurorian                  | 1.12.2-Release      | theaurorian-1.12.2-release-may3021.jar           | None                                     |
	| LCH   | thesummoner                  | 1.0.1-beta          | thesummoner-1.0.1.jar                            | None                                     |
	| LCH   | tips                         | 1.0.9               | Tips-1.12.2-1.0.9.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | torchmaster                  | 1.8.5.0             | torchmaster_1.12.2-1.8.5.0.jar                   | None                                     |
	| LCH   | toughnessbar                 | @VERSION@           | toughnessbar-2.4.jar                             | None                                     |
	| LCH   | treeharvester                | 4.0                 | treeharvester_1.12.2-4.0.jar                     | None                                     |
	| LCH   | tumbleweed                   | 1.12-0.4.7          | tumbleweed-1.12-0.4.7.jar                        | None                                     |
	| LCH   | villagernames                | 3.4                 | villagernames_1.12.2-3.4.jar                     | None                                     |
	| LCH   | weather2                     | 1.12.1-2.6.12       | weather2-1.12.1-2.6.12.jar                       | None                                     |
	| LCH   | wolfarmor                    | 3.7.5               | wolfarmor-1.12.2-3.7.5-universal-signed.jar      | e94e38a605842477f3ec218e6fcf781f6b3f7f89 |
	| LCH   | xpbook                       | v2.0                | xptome-1.12.2-v2.0.jar                           | None                                     |
	| LCH   | dshuds                       | 3.6.0.0             | DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | jade                         | 0.1.0               | Jade-0.1.0.jar                                   | None                                     |
	| LCH   | kiwi                         | 0.5.3.32            | Kiwi-1.12.2-0.5.3.32.jar                         | None                                     |
	| LCH   | modwinder                    | 1.1                 | Ladylib-2.3.jar                                  | None                                     |
	| LCH   | ladylib                      | 2.3                 | Ladylib-2.3.jar                                  | None                                     |
	| LCH   | lumen                        | 0.4.1               | lumen-Beta 0.4.2.jar                             | None                                     |
	| LCH   | thebetweenlands              | 3.8.0               | TheBetweenlands-3.8.0-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCH   | midnight                     | 0.3.5               | themidnight-0.3.5.jar                            | None                                     |
	| LCH   | justthetips                  | 1.12-1.0.1.1        | justthetips-1.12-1.0.1.1.jar                     | None                                     |

	Loaded coremods (and transformers): 
Snow! Real Magic! (SnowRealMagic-1.12.2-0.5.6.jar)
  
ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
MixinBooter (.mixinbooter-4.0.jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoliASM (loliasm-4.4.1.jar)
  
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.8.0-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Pick Up Notifier (PickUpNotifier-v1.1.5-1.12.2.jar)
  com.fuzs.pickupnotifier.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
KonkreteCore (konkrete_1.3.0_MC_1.12-1.12.2.jar)
  
FMCore (fancymenu_2.3.6_MC_1.12-1.12.2.jar)
  
Sneaky Curses (SneakyCurses-v1.0.1-1.12.2.jar)
  com.fuzs.sneakycurses.asm.ClassTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
MSICCoreMod (MyServerIsCompatible-1.12.2-1.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Aqua Acrobatics Transformer (AquaAcrobatics-v1.3.5-1.12.2.jar)
  
CharmLoadingPlugin (Charm-1.12.2-1.4.1.jar)
  svenhjol.charm.base.CharmClassTransformer
WolfArmorCore (wolfarmor-1.12.2-3.7.5-universal-signed.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9664' Renderer: 'Intel(R) UHD Graphics 600'
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.9664
	OpenGlRenderer: Intel(R) UHD Graphics 600
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by Jackc2021** [comment]
sorry for the long log

**Comment by Jackc2021** [comment]
i think spartan compat might be the issue, i know it's caused issues for me before. also i forgot to mention it's 1.12.2

**Comment by Jackc2021** [comment]
it was spartan compat
